language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.3"
before_install:
  - wget -P ~ http://mafft.cbrc.jp/alignment/software/mafft-7.205-with-extensions-src.tgz
  - tar -zxvf ~/mafft-7.205-with-extensions-src.tgz -C ~
  - (cd ~/mafft-7.205-with-extensions/core/ && make clean && make && sudo make install)
  - which mafft
script: rake test
addons:
  code_climate:
    repo_token: 53b568ce70cefc91f4ee27f1ee901136d863d90ef6f8155cee2ba9b1248dc502