language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.3"
before_install:
  - pwd
  - bundle install --jobs=3 --retry=3
  - pwd
  - wget -P ~ http://mafft.cbrc.jp/alignment/software/mafft-7.205-with-extensions-src.tgz
  - tar -zxvf ~/mafft-7.205-with-extensions -C ~
  - (cd ~/mafft-7.205-with-extensions/core/ && make clean && make && sudo make install)
  - which mafft
  - pwd
script: rake test
