language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.3"
before_install:
  - pwd
  - rake
  - pwd
  - cd
  - wget http://mafft.cbrc.jp/alignment/software/mafft-7.205-with-extensions-src.tgz
  - gunzip -cd mafft-7.205-with-extensions-src.tgz | tar xfv -
  - cd mafft-7.205-with-extensions/core/
  - make clean
  - make 
  - sudo make install
  - which mafft
  - pwd
  - cd -
  - pwd
script: rake test
